openapi: 3.0.2
info:
  title: Contract for fraud prevention APIS.
  version: 1.0.0
paths:
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              examples:
                OK:
                  value:
                    message: pong
          description: Ejemplo
      security:
        - access_token: []
      operationId: ping
      summary: Ping
  /v1/fraud/prevention/individuals/analytics:
    get:
      tags:
        - Fraude prevention
      description: |
        Se tienen en cuentas las siguientes reglas sobre los usuarios:
        - Nuevos usuarios. (usuarios con antiguedad en nuestro sistema < 7 dias.)
        - Cantidad de pagos rechazados en el último día.
        - Monto acumulado total (en usd) de pagos por usuario en la última semana.
      summary: API analitica de los usuarios.
      parameters:
        - $ref: "#/components/parameters/HeaderApiKey"
        - $ref: "#/components/parameters/PaginationPage"
        - $ref: "#/components/parameters/PaginationLimit"
      responses:
        "200":
          description: Respuesta exitosa.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetFraudPreventionAnalyticsResponse"
        "401":
          description: Unauthorized
          $ref: "#/components/responses/UNAUTHORIZED_RESPONSE"
        "500":
          description: Internal server error.
          $ref: "#/components/responses/INTERNAL_SERVER_ERROR"
components:
  schemas:
    RuleResponse:
      description: Reglas para evitar el fraude tecnologico.
      type: object
      required:
        - user_id
        - is_new_user
        - qty_rejected_1d
        - total_amt_7d
      properties:
        user_id:
          description: Identificador del usuarios.
          type: integer
          example: 1
        is_new_user:
          description: |
            Indica si el usuario es considerado "nuevo" basado en la fecha de creación de su cuenta.
            - **true**: El usuario tiene menos de 7 días desde su registro.
            - **false**: El usuario tiene más de 7 días desde su registro.
          type: boolean
          example: true
        qty_rejected_1d:
          description: Cantidad de pagos rechazados en el último dia.
          type: integer
          example: 5
        total_amt_7d:
          description: Monto acumulado total (en usd) de pagos por usuario en la última semana.
          type: number
          example: 100.5
    GetFraudPreventionAnalyticsResponse:
      description: Respuesta con paginado y datos.
      type: object
      required:
        - page
        - per_page
        - total_pages
        - total_count
        - data
      properties:
        page:
          type: integer
          description: Página actual.
          example: 1
        per_page:
          type: integer
          description: Cantidad de elementos por página.
          example: 10
        total_pages:
          type: integer
          description: Número total de páginas disponibles.
          example: 10
        total_count:
          type: integer
          description: Número total de elementos disponibles.
          example: 50
        data:
          type: array
          items:
            $ref: "#/components/schemas/RuleResponse"

    ErrorResponse:
      description: ""
      required:
        - message
        - error_code
      type: object
      properties:
        message:
          description: Descripcion del error
          type: string
        error_code:
          description: Código que representa el error que se produjo
          type: string
        details:
          description: Detalle del error
          type: object
  responses:
    INTERNAL_SERVER_ERROR:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            INTERNAL_SERVER_ERROR:
              value:
                message: Unexpected error. Please try again.
                error_code: internal_server_error
      description: Internar server error.
    UNAUTHORIZED_RESPONSE:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            INVALID_CREDENTIALS:
              value:
                message: Invalid or missing credentials
                error_code: invalid_credentials
      description: Unauthorized.
  parameters:
    PaginationPage:
      description: Indica el número de página.
      name: page
      in: query
      required: false
      example: 1
      schema:
        type: integer
        default: 1
    PaginationLimit:
      description: Indica el número de elementos que se devolverán en la página
      name: limit
      in: query
      required: false
      example: 10
      schema:
        type: integer
        default: 10
    HeaderApiKey:
      name: api-key
      description: Mecanismo de seguridad para poder acceder a la API.
      in: header
      required: true
      schema:
        type: string
      example: Z1AhMDI5YzYtYWY2NC00ODYwLWEwMTUtNjMxMjdlODBiYTM1

  securitySchemes:
    access_token:
      scheme: bearer
      type: http
